layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

 social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: seiedeshivamoosavi
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Data Science
    # web_url: https://github.com/topics/css
    image_url: https://th.bing.com/th/id/OIP.3u2JTNppmknuX60gagk5ZAHaEK?w=312&h=180&c=7&o=5&dpr=1.25&pid=1.7

  - name: Programming
    image_url: https://th.bing.com/th/id/OIP.WW91rHjKmkUsPztKXd7yqQHaE8?w=231&h=180&c=7&o=5&dpr=1.25&pid=1.7
    
  - name: Statistics
    #web_url: https://github.com/topics/sass
    image_url: https://th.bing.com/th/id/OIP.JkBw1Gy5w8NZYHN5Cr31uwHaE7?w=273&h=181&c=7&o=5&dpr=1.25&pid=1.7
